name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.AWS_INSTANCE_IP }}
          username: ubuntu

      - name: Install PHP and dependencies
        run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader  --ignore-platform-reqs

      - name: Deploy to EC2
        run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@***:/var/www/packult

      - name: Clear SSH key
        run: rm -f $HOME/.ssh/id_rsa
